### ISSUE TITLE
Make findOrOpenInPrivateWindow actually work

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#1]
This is stubbed out now, make it work.

**Comment by gregglind** [comment]
So, what's the design here?

**Comment by monicachew** [comment]
The current plan is the dumbest plan: open a new window in private browsing mode if the user clicks "yes" on the panel.

**Comment by gregglind** [comment]
https://github.com/gregglind/git-testpilot/blob/jetpack/extension/data/tp-browser-notification.html has some ideas about panel notices and actions.

**Comment by monicachew** [comment]
keeler fixed this in https://github.com/mozilla/blushproof/blob/df8ff95c6d1efb313ec4356f4ff9aed38d36f159/lib/bpUI.js
