### ISSUE TITLE
naughty list should not incriminate the user

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#11]
We probably shouldn't expose the list of sites that user wants to keep private in the code itself, especially if we are going to do things like "remember sites that users open in PB mode and add them to the list".

Instead, we should probably do something like keep hashes of URLs on the list, so that if someone finds the list it'll be marginally more difficult to see that the user wants to keep pokerstars or whatever in PB mode.

Obviously this breaks the substring matching that you're using to check to see if new URLs should be opened in PB mode, since hashes don't preserve substrings.

**Comment by mozkeeler** [comment]
I just pushed a branch implementing (so I claim) a bloom filter in lib/bpUtil.js. test/test-main.js has some initial tests for it (it also demonstrates how it's supposed to be used).

**Comment by monicachew** [comment]
Awesome! I look forward to the pull request :) 

----- Original Message -----

**Comment by monicachew** [comment]
@daviddahl are we spamming you? I think there was no way to give you collaborator access to cookiemonster without adding you to blushproof team, but I can ask jsocol to make a cookiemonster team. That's probably cleaner.

**Comment by mozkeeler** [comment]
fixed by #53
