### ISSUE TITLE
Use nsIContentPolicy to intercept HTTP requests

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#2]
Don't do string matching on the top-level url bar. Use nsIContentPolicy to intercept them and restrict applying blushproof to the top-level window.

**Comment by gregglind** [comment]
This might not be "early enough" for all things.  Also everything isn't a URL load.  I claim that all the common sites should be caught even before search happens.  Maybe good excuse to start writing the feature contract :)

**Comment by monicachew** [comment]
No doubt that's true -- but this is in the spirit of "don't make the perfect the enemy of the good", for incremental progress :)
