### ISSUE TITLE
move whitelistDomains and blushlist to simple-storage

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#24]
blushlist is currently immutable, but users should be able to add to it. Users can already add to whitelistDomains but that doesn't persist across restarts.

I suggest using simple-storage: https://addons.mozilla.org/en-US/developers/docs/sdk/1.9/packages/addon-kit/simple-storage.html

**Comment by monicachew** [comment]
keeler will move blushlist to simple storage when moving URLs to hashes.

**Comment by mozkeeler** [comment]
Right - except I forgot to do that in the recent pull request :-/
I guess ignore that for now until I add this bit...

**Comment by mozkeeler** [comment]
fixed by #53
