### ISSUE TITLE
We need a logo.

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#26]
Something like http://img-cache.cdn.gaiaonline.com/043e246d060a241f7bf9574ae988d0ab/http://i77.photobucket.com/albums/j80/Kiyanra/fox%20girls/fox_fire-2.jpg but less porny.

**Comment by monicachew** [comment]
OK this one's pretty good, too: http://www.quickmeme.com/meme/4g0h/

**Comment by monicachew** [comment]
I found a bunch of foxkeh pictures and put one of them on the wiki: https://github.com/mozilla/blushproof/wiki

Ok?

**Comment by mozkeeler** [comment]
Looks great!

**Comment by monicachew** [comment]
Yay! I wanted to make it actually blush, but maybe I'll save that task for when I need to procrastinate later ;)
