### ISSUE TITLE
use exisitng windowTracker rather than reinventing the wheel

### ISSUE THREAD

**Issue by gregglind** [mozilla/blushproof#27]
@monicachew 

Note:  require('deprected/window-tracker') is only deprecated because it is moving around in the sdk:  

See:  https://addons.mozilla.org/en-US/developers/docs/sdk/latest/modules/sdk/deprecated/window-utils.html

Use that, and its `onTrack` event rather than reinventing the wheel :)

**Comment by monicachew** [comment]
windows.on("open", eventlistener) is not deprecated, and is marked as stable in the sdk. Why is that reinventing the wheel?

**Comment by monicachew** [comment]
https://addons.mozilla.org/en-US/developers/docs/sdk/latest/modules/sdk/windows.html + search for windows.on('open'

**Comment by gregglind** [comment]
Tracker cleans up both the on('open') and the on('close') bits, which helps
prevent leaks.  It also ensures that any already open windows get tracked
in the same way.  It's an easy place to have weird edge cases.

**Comment by mozkeeler** [comment]
Where are we reinventing the wheel?

**Comment by monicachew** [comment]
I think Gregg was referring to 9755571718454c66e8dc8e4da2b727ba778283cb, which was never merged in.
