### ISSUE TITLE
Add social/timewaster categories to blushlist.js

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#31]

**Comment by gregglind** [comment]
Any item can probably have multiple categories, eh?

**Comment by monicachew** [comment]
No doubt it's many to many. However, I'm not sure if we need to support multiple categories per item quite yet, since we're not actually using the category for anything?

On the other hand, keeler was mentioning that if we ever do expose a UI it would probably be to select which categories are blushable...
