### ISSUE TITLE
check search results page for hits on url blushlist to add query terms to the blushlist

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/blushproof#40]
Say a user wants to go to "somesite.com" - they'll type this in the search bar (or in a search page), go to the results page, and click on the link to "somesite.com". If the navigation to the site would cause blushproof to prompt the user, we should probably catch this at the search step. One solution would be to also check the url blushlist when checking the search term list.

**Comment by monicachew** [comment]
Yeah, this is what Jesse Ruderman recommended. Heavier weight, though.

**Comment by monicachew** [comment]
Incidentally I think this is how a lot of netnanny type extensions work, I unpacked the CloudACL addon recently and found similar flows.
