### ISSUE TITLE
have a "forget this site" button

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#43]
If a person navigates to a site without setting PB mode, let them forget the site from their history and also ask if they want to add it to the blushlist.

**Comment by monicachew** [comment]
@gregglind says to use a simple thing from require("widget")

**Comment by monicachew** [comment]
Probably best to follow this down:

http://mxr.mozilla.org/mozilla-central/source/browser/components/preferences/privacy.xul#135
                onclick="gPrivacyPane.clearPrivateDataNow(false); return false;"

**Comment by monicachew** [comment]
We may be able to do something similar to this, not sure if it's possible to restrict to one site though:

http://mxr.mozilla.org/mozilla-central/source/browser/components/preferences/in-content/privacy.js#478
  clearPrivateDataNow: function (aClearEverything)
479   {
480     var ts = document.getElementById("privacy.sanitize.timeSpan");
481     var timeSpanOrig = ts.value;
482     if (aClearEverything)
483       ts.value = 0;
484 
485     const Cc = Components.classes, Ci = Components.interfaces;
486     var glue = Cc["@mozilla.org/browser/browserglue;1"]
487                  .getService(Ci.nsIBrowserGlue);
488     glue.sanitize(window);
489 
490     // reset the timeSpan pref
491     if (aClearEverything)
492       ts.value = timeSpanOrig;
493   },
494

**Comment by jdm** [comment]
http://mxr.mozilla.org/mozilla-central/source/toolkit/forgetaboutsite/ForgetAboutSite.jsm

**Comment by monicachew** [comment]
There's now a "blush this" button which adds a site to the blushlist and optionally lets you forget it, except clearing the awesomebar doesn't seem to work.

**Comment by monicachew** [comment]
Closing since there's another bug for the awesomebar.
