### ISSUE TITLE
update wiki with which versions of FF are supported

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#45]
Keeler, I think you said FF 20 but not Fennec, I can't remember.

**Comment by mozkeeler** [comment]
As I understand it, per-window private browsing landed in desktop FF20. I don't know if it's also in mobile, and even if it is, I don't know if blushproof will work on mobile (although I don't think there's anything desktop-specific in it...)

**Comment by monicachew** [comment]
Fair enough, I couldn't even remember the desktop version :) 

----- Original Message -----

**Comment by jdm** [comment]
Mobile is getting private tabs in 20 as well.

**Comment by monicachew** [comment]
Thanks @jdm that's really exciting!
