### ISSUE TITLE
Agree on a code style guidelines

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/blushproof#5]
I propose we follow https://developer.mozilla.org/en-US/docs/Developer_Guide/Coding_Style where it makes sense to do so (obviously, a lot of the Mozilla-specific things won't apply, but for things like whitespace, where to put braces, etc.)

In particular:
- 2 spaces, not tabs
- if (...) {
  } else {
  }
- semicolons after statements, but not top-level function declarations
- 80-character lines if possible
- no trailing whitespace (or whitespace on empty lines)

**Comment by monicachew** [comment]
SGTM.

**Comment by monicachew** [comment]
I used to follow these, way back when I wrote JS:
http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml

I think they are a superset of the Mozilla ones.
