### ISSUE TITLE
integrate with micropilot

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#59]
1. Measure how often people hit "yes, open in PB mode"
2. Measure how often people hit "cancel, open in regular"
3. Measure how often blushlist triggers, as a proportion of normal browsing
4. Measure how often people hit "blush this" button
5. Measure how often people enter PB mode, independent of the blushlist
6. Measure how often people use the "Clear history" or other session data
7. What other hints do users give that they might be embarrassed? (hitting esc during page load)

**Comment by gregglind** [comment]
This is create, and if you want help with it, I am working on making this easy at:  https://github.com/gregglind/micropilot/issues/22

**Comment by monicachew** [comment]
Thanks, that would be awesome! 

----- Original Message -----

**Comment by monicachew** [comment]
for 5., look for events related to last-pb-context-exited

**Comment by monicachew** [comment]
or perhaps https://mxr.mozilla.org/mozilla-central/source/docshell/base/nsIPrivacyTransitionObserver.idl?

**Comment by jdm** [comment]
nsIPrivacyTransitionObserver.idl is on its way out.

**Comment by mozkeeler** [comment]
opting in to private browsing / using panels bug: https://bugzilla.mozilla.org/show_bug.cgi?id=816257
