### ISSUE TITLE
what categories do we want to include on install?

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#60]
We have:
1. adult
2. gossip
3. social

We should also include
1. gambling?
2. drug related queries, e.g. recreational drug use
3. medical, e.g. do i have prostate cancer
4. mental health issues, suicide and depression (medical)
5. gaming (video games, board game geek)
6. money, bankruptcy, debt collection
7. dieting, body issues (related medical)
8. crimes, how to get away with

**Comment by mozkeeler** [comment]
guns?

**Comment by monicachew** [comment]
Sure, guns. I've been poking around and recording findings here: https://github.com/mozilla/blushproof/wiki/Related-Work
