### ISSUE TITLE
aws server to receive micropilot events

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#66]
We need a server that receive JSON posts.

**Comment by monicachew** [comment]
https://github.com/mozilla/awsbox/blob/master/doc/TUTORIAL.md
107.22.82.223

**Comment by monicachew** [comment]
1. host blushproof.dyndns.org
2. need self-signed cert installed in cert db
3. write node server that is ssl enabled and sticks posts into mysql

**Comment by monicachew** [comment]
Code will be in /server

**Comment by mozkeeler** [comment]
1. host is now blushproof.org
2. bought an actual cert
3. I've been having success with sqlite instead of a full-fledged mysql setup

**Comment by monicachew** [comment]
YAY!!! :) 

----- Original Message -----
