### ISSUE TITLE
Write design doc for blushproof

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#70]
like https://github.com/mozilla/cookiemonster/blob/master/designdoc.md

This needs to happen before micropilot integration so we explicitly agree on what we're collecting

Also it will inform the privacy policy

**Comment by monicachew** [comment]
Added to https://github.com/mozilla/blushproof/blob/master/doc/designdoc.md

**Comment by mozkeeler** [comment]
I feel like we should add a fuzz factor or otherwise limit the accuracy of the timestamps on the events we receive. Maybe just the date is enough?

**Comment by monicachew** [comment]
The timestamp is mainly for us to be able to check changes over time. I could modulo to the nearest hour. Hour is useful as a sanity check, we should see more data over the middle of the day than when people are sleeping. Day also gives as a sanity check (Wednesday is the highest traffic day) but less so -- and we won't be able to do things like gauge how often people need PB mode during work hours vs outside, etc.

We can also make it explicit that we discard personids after computing daily active users.

**Comment by monicachew** [comment]
All traffic that I've seen follows curves like this: http://www.socialnomics.net/2010/11/29/best-time-to-post/

**Comment by monicachew** [comment]
Marking done since we chatted about this last week.
