### ISSUE TITLE
switch to require(timer) instead of fuse

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#87]
Gregg says Fuse is intended for doing things once.

**Comment by monicachew** [comment]
https://addons.mozilla.org/en-US/developers/docs/sdk/latest/modules/sdk/timers.html

use setInterval

**Comment by monicachew** [comment]
1. Keep last upload time in simple-storage
2. If interval time has passed since last upload, then upload
3. Also, set a timer to upload every interval. This timer can be instantiated on every run.
4. Always clear after we upload.

**Comment by mozkeeler** [comment]
Maybe 3 should be "set a timer at an interval less than the upload interval that does 2".

**Comment by mozkeeler** [comment]
Just fyi, we're waiting on some improvements in micropilot (see issues 38/39 in that repo).
