### ISSUE TITLE
blushproofing posting

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#95]
So far, blushproof is about preventing embarrassment for viewing sites/reading. It would be super fun to enable blush-resistance for posting/writing. I like the concept of this API very much:

http://help.sentiment140.com/api

Is this worth pursuing?

**Comment by monicachew** [comment]
There's a bunch of these, here's another: http://www.alchemyapi.com/

**Comment by mozkeeler** [comment]
What would be really cool is if we could detect when someone is about to over-share something (e.g. "This appears to be a post directed at your friends, but it will be viewable by your coworkers, family, and the pope. Continue?")

**Comment by monicachew** [comment]
That would be really cool, but tough given the difference in sharing semantics/implementation across major sites. Something that would be easier would be "This post appears to be negative, are you sure you want to post it?" Unfortunately the APIs I found don't give any category beyond negative, which would also be useful. 

----- Original Message -----
