### ISSUE TITLE
get on AMO

### ISSUE THREAD

**Issue by monicachew** [mozilla/blushproof#96]
Clicking links to download then manually installing is so lame...

**Comment by monicachew** [comment]
Filed (we are at position 140!), request viewable at https://addons.mozilla.org/en-US/firefox/addon/blushproof/. @mozkeeler we need to change the id in package.json not to be blushproof@ux. I filed a ticket to get us blushproof@mozilla.org.

**Comment by monicachew** [comment]
We were rejected for not being packaged with a release SDK. Repackaging led to a bunch of errors.

Jetpack module version mismatch

Warning: A file in the Jetpack add-on does not match the SDK version specified in harness-options.json.

Module: resources/micropilot/lib/indexed-db-17.js

Versions: 1.14/1.12-dev
resources/micropilot/lib/indexed-db-17.js

```
Prev
Top
Next
```

Security Tests
0 errors, 2 warnings
Parse error: tag closed before opened

Warning: Markup tags cannot be closed before they are opened. Perhaps you were just a little overzealous with forward-slashes?

Tag "td" closed before it was opened
resources/blushproof/data/blushbutton.html
20
21
22
<body>
<img id="icon" src="blushproof-16.png"></img></td>
<span id="text">Blush This!</span></td>
Parse error: tag closed before opened

Warning: Markup tags cannot be closed before they are opened. Perhaps you were just a little overzealous with forward-slashes?

Tag "td" closed before it was opened
resources/blushproof/data/blushbutton.html
21
22
23
<img id="icon" src="blushproof-16.png"></img></td>
<span id="text">Blush This!</span></td>
</body>

```
Prev
Top
Next
```

Extension Tests
0 errors, 7 warnings
Usage of non-SDK interface

Warning: This SDK-based add-on uses interfaces that aren't part of the SDK.
resources/blushproof/lib/bpContentPolicy.js
7
8
const { Ci } = require("chrome");
const { Class } = require("sdk/core/heritage");
Usage of non-SDK interface

Warning: This SDK-based add-on uses interfaces that aren't part of the SDK.
resources/blushproof/lib/main.js
7
8
const { Cc, Ci } = require("chrome");
let bpContentPolicy = require("bpContentPolicy");
Potentially unsafe preference branch referenced

Warning: Extensions should not alter preferences in the `general.useragent.` preference branch
resources/micropilot/lib/micropilot.js
695
696
697
let { promise, resolve } = defer();
let LOCALE_PREF = "general.useragent.locale";
let UPDATE_CHANNEL_PREF = "app.update.channel";
Usage of non-SDK interface

Warning: This SDK-based add-on uses interfaces that aren't part of the SDK.
resources/micropilot/lib/micropilot.js
72
73
74
/_!_/
const { Cc, Ci, Cu } = require("chrome");
const xulApp = require('sdk/system/xul-app');
Usage of non-SDK interface

Warning: This SDK-based add-on uses interfaces that aren't part of the SDK.
resources/blushproof/lib/bpUI.js
22
23
const { Cc, Ci, Cu } = require("chrome");
// The second param avoids polluting the scope
Usage of non-SDK interface

Warning: This SDK-based add-on uses interfaces that aren't part of the SDK.
resources/blushproof/lib/bpUtil.js
7
8
const { Cc, Ci } = require("chrome");
let querystring = require("querystring");
Usage of non-SDK interface

Warning: This SDK-based add-on uses interfaces that aren't part of the SDK.
resources/micropilot/lib/indexed-db.js
11
12
const { Cc, Ci } = require("chrome");
const { id } = require("self");

```
Prev
Top
Next
```

Localization Tests
0 errors, 0 warnings
All tests passed successfully.

```
Prev
Top
Next
```

Compatibility Tests
0 errors, 0 warnings
All tests passed successfully.

**Comment by monicachew** [comment]
I think we can ignore the chrome warnings, constify the pref warning, and fix the td tags.

**Comment by monicachew** [comment]
Aww, a lot of these are for micropilot :(

**Comment by monicachew** [comment]
https://addons.mozilla.org/en-US/firefox/addon/blushproof/

Resubmitted. Unfortunately because I had to change the UUID I had to delete the old listing and add a new one, so we have to start over in the queue.

**Comment by monicachew** [comment]
@mozkeeler I need your AMO name again (I had to recreate the listing and lost it)

**Comment by mozkeeler** [comment]
I changed it to mozkeeler to match github.

**Comment by monicachew** [comment]
Deleted indexed-db-17.js and resubmitted.

**Comment by monicachew** [comment]
Updated version and resubmitted. AMO can't handle xpis with the same version and different content.

**Comment by monicachew** [comment]
This eventually got preliminary review, closing for now.
